amqp_port: 443
display_name: ESGF-WPS-local
engine:
  max_workers_per_node: 1
  provider:
    init_blocks: 1
    max_blocks: 1
    min_blocks: 0
    type: LocalProvider
    worker_init: |
      conda activate esgf-compute-flows-dev
  type: GlobusComputeEngine
allowed_functions:
  - <add-your-function-uuid-here>